import Head from "next/head";
import { Text, Heading } from "@/components/Text";
import privacyPolicy from "@/data/privacy-policy.json";

// Refund policy is for the online merchandise store
export default function PrivacyPolicy() {
  return (
    <>
      <Head>
        <title>Evolutz Academy | Refund Policy</title>
        <meta name="description" content="Evolutz Academy refund policy" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="my-20 px-5 md:px-8">
        <div className="mx-auto max-w-[800px]">
          <Heading
            as="h1"
            size="sectionSub"
            family="secondary"
            className="mb-8"
          >
            Evolutz Privacy Policy
          </Heading>
          <div className="mb-12 font-light">
            <Text as="p" family="secondary" className="mb-4">
              Last updated: September 22, 2022
            </Text>
            <Text as="p" family="secondary" className="mb-4">
              This Privacy Policy describes the Evolutz’s policies and
              procedures on the collection, use and disclosure of your
              information when you use our Website or App and tells you about
              your privacy rights.
            </Text>
            <Text as="p" family="secondary" className="mb-4">
              We use your personal information to provide and improve our
              Services. By using our Services, you agree to the collection and
              use of information in accordance with this Privacy Policy.
            </Text>
          </div>
          <ol className="font-nunito font-light">
            <li className="mb-12">
              <h2 className="mb-4 font-bold text-xl">
                A. Interpretation and Definitions
              </h2>
              <article className="mb-6">
                <h3 className="mb-2 font-semibold text-lg">Interpretation</h3>
                <Text as="p" className="mb-1">
                  The following definitions shall have the same meaning
                  regardless of whether they appear in singular or in plural.
                </Text>
              </article>
              <article className="mb-6">
                <h3 className="mb-2 font-semibold text-lg">Definitions</h3>
                <Text as="p" className="mb-1">
                  For the purposes of this Privacy Policy:
                </Text>
                <ul className="ml-4 pl-4 list-disc">
                  <li>
                    Account means a unique account created for you to access our
                    Services.
                  </li>
                  <li>
                    Application (or “App”) means any software program provided
                    by us and downloaded by you on any electronic device.
                  </li>
                  <li>
                    EVOLUTZ (referred to as either EVOLUTZ,we, or in this
                    Agreement) refers to Evolutz Inc., a corporation established
                    pursuant to the Canada Business Corporations Act.
                  </li>
                  <li>
                    Cookies are small files that are placed on your computer,
                    mobile device or any other device by a Website or
                    Application, containing the details of your browsing history
                    on that Website among its many uses.
                  </li>
                  <li>
                    Device means any device that can access our Services, such
                    as a computer, a cellphone or a digital tablet.
                  </li>
                  <li>
                    Personal Data and Information is any information that
                    relates to an identified or identifiable individual.
                  </li>
                  <li>
                    Service refers to the Application, the Website, and any
                    services provided on either.
                  </li>
                  <li>
                    Service Provider means any natural or legal person who
                    processes the data on behalf of EVOLUTZ. It refers to
                    third-party companies engaged or individuals employed by
                    EVOLUTZ to facilitate the Service, to provide the Service on
                    behalf of EVOLUTZ, to perform services related to the
                    Service or to assist EVOLUTZ in analyzing how the Service is
                    used.
                  </li>
                  <li>
                    Usage Data refers to data collected automatically, either
                    generated by the use of the Service or from the Service
                    infrastructure itself (for example, the duration of a page
                    visit).
                  </li>
                  <li>
                    Website refers to EVOLUTZACADEMY.com, accessible from
                    www.evolutzacademy.com
                  </li>
                  <li>
                    “you” (or “your”) means the individual accessing or using
                    the Service, or the other entity on behalf of which such
                    individual is accessing or using the Service, as applicable.
                  </li>
                </ul>
              </article>
            </li>
            <li className="mb-12">
              <h2 className="mb-4 font-bold text-xl">
                B. Collecting and Using your Personal Data
              </h2>
              <article className="mb-6">
                <Text as="p" className="mb-1">
                  While using our Website, App, or Services, we may ask you to
                  provide us with certain personally identifiable information
                  that can be used to contact or identify you. Personally
                  identifiable information may include, but is not limited to:
                </Text>
                <ul className="ml-4 pl-4 list-disc">
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Phone number</li>
                  <li>Banking or other financial information</li>
                  <li>Address, province, postal code, city</li>
                  <li>Usage data</li>
                </ul>
              </article>
              <article className="mb-6">
                <h3 className="mb-2 font-semibold text-lg">Usage Data</h3>
                <Text as="p" className="mb-4">
                  Usage Data is collected automatically when using the Service.
                  <br />
                  Usage Data may include information such as your device
                  Internet Protocol address (e.g. IP address), browser type,
                  browser version, the pages of our Service that you visit, the
                  time and date of your visit, the time spent on those pages,
                  unique device identifiers and other diagnostic data. <br />{" "}
                  When you access the Service by or through a mobile device, we
                  may collect certain information automatically, including, but
                  not limited to, the type of mobile device you use, your mobile
                  device unique ID, the IP address of your mobile device, your
                  mobile operating system, the type of mobile Internet browser
                  you use, unique device identifiers and other diagnostic data.{" "}
                  <br />
                  We may also collect information that your browser sends
                  whenever you visit our Service or when you access the Service
                  by or through a mobile device.
                </Text>
                <article className="mb-4">
                  <h4 className="mb-2 font-semibold text-md">
                    Tracking Technologies and Cookies
                  </h4>
                  <Text as="p" className="mb-2">
                    We use Cookies and similar tracking technologies to track
                    the activity on our Services and store certain information.
                    Tracking technologies used are beacons, tags, and scripts to
                    collect and track information and to improve and analyze our
                    Service. The technologies we use may include:
                  </Text>
                  <ul className="ml-4 mb-2 pl-4 list-disc">
                    <li>
                      Cookies or Browser Cookies: A cookie is a small file
                      placed on your device. You can instruct your browser to
                      refuse all cookies or to indicate when a cookie is being
                      sent. However, if you do not accept cookies, you may not
                      be able to use some parts of our Service. Unless you have
                      adjusted your browser setting so that it will refuse
                      cookies, our Service may use cookies.
                    </li>
                    <li>
                      Flash Cookies: Certain features of our Service may use
                      local stored objects (or Flash Cookies) to collect and
                      store information about your preferences or your activity
                      on our Service. Flash Cookies are not managed by the same
                      browser settings as those used for browser cookies.
                    </li>
                    <li>
                      Web Beacons. Certain sections of our Service and our
                      emails may contain small electronic files known as web
                      beacons (also referred to as clear gifs, pixel tags, and
                      single-pixel gifs) that permit EVOLUTZ, for example, to
                      count users who have visited those pages or opened an
                      email and for other related website statistics (for
                      example, recording the popularity of a certain section and
                      verifying system and server integrity).
                    </li>
                  </ul>
                  <Text as="p" className="mb-1">
                    Cookies can be Persistent or Session Cookies. Persistent
                    Cookies remain on your personal computer or mobile device
                    when you go offline, while Session Cookies are deleted as
                    soon as you close your web browser.
                  </Text>
                  <Text as="p" className="mb-2">
                    We use both Session and Persistent Cookies for the purposes
                    set out below:
                  </Text>
                  <ul className="ml-4 mb-2 pl-4 list-disc">
                    <li>
                      <h5 className="font-semibold">
                        Necessary / Essential Cookies
                      </h5>
                      <Text as="p" className="mb-2">
                        Type: Session Cookies <br />
                        Administered by: Us <br />
                        Purpose: These cookies are essential to provide you with
                        services available through the Service and to enable you
                        to use some of its features. They help to authenticate
                        users and prevent fraudulent use of user accounts.
                        Without these cookies, the services that you have asked
                        for cannot be provided, and we only use these cookies to
                        provide you with those services.
                      </Text>
                    </li>
                    <li>
                      <h5 className="font-semibold">Functionality Cookies</h5>
                      <Text as="p" className="mb-2">
                        Type: Persistent Cookies <br />
                        Administered by: Us <br />
                        Purpose: These cookies allow us to remember choices you
                        make when you use the Service, such as remembering your
                        login details or language preference. The purpose of
                        these cookies is to provide you with a more personal
                        experience and to avoid you having to re-enter your
                        preferences every time you use the Service.
                      </Text>
                    </li>
                  </ul>
                </article>
                <article>
                  <h4 className="mb-2 font-semibold text-md">
                    Use of Your Personal Data
                  </h4>
                  <Text as="p" className="mb-2">
                    We only process personal information for the activities
                    mentioned below after considering the potential risks to
                    your privacy—for example, by providing clear transparency
                    into our privacy practices, offering you control over your
                    personal information where appropriate, limiting the
                    information we keep, limiting what we do with your
                    information, who we send your information to, how long we
                    keep your information, or the technical measures we use to
                    protect your information.
                  </Text>
                  <article className="mb-2">
                    <Text as="p" className="mb-1">
                      EVOLUTZ may use Personal Data for the following purposes:
                    </Text>
                    <ul className="ml-4 pl-4 list-disc">
                      <li>
                        To provide and maintain our Service, including to
                        monitor the usage of our Service.
                      </li>
                      <li>
                        To manage your account: to manage your registration as a
                        user of the Service. The Personal Data you provide can
                        give you access to different functionalities of the
                        Service that are available to you as a registered user.
                      </li>
                      <li>
                        To contact you: To contact you by email, telephone
                        calls, SMS, or other equivalent forms of electronic
                        communication, such as a mobile application push
                        notifications regarding updates or informative
                        communications related to the functionalities, products
                        or contracted services, including security or system
                        updates, when necessary or reasonable for their
                        implementation.
                      </li>
                      <li>
                        To provide you with marketing information: To provide
                        you with news and general information about other
                        services and events which we facilitate that are similar
                        to those that you have already expressed an interest in
                        or enquired about unless you have opted not to receive
                        such information. If you have consented to receiving
                        marketing information, you may contact us at any time to
                        opt out of receiving further marketing communications
                        from us.
                      </li>
                      <li>
                        To manage your requests: to attend to and manage your
                        requests to us.
                      </li>
                      <li>
                        For transfers: We may use your information to evaluate
                        or conduct a restructuring, reorganization, dissolution,
                        or other sale or transfer of some or all of our assets,
                        in which Personal Data held by us about our Service
                        users is among the assets transferred. We may further
                        use your information that involves transferring it to
                        other third parties EVOLUTZ contracts in order to
                        deliver its Services.
                      </li>
                      <li>
                        For other purposes: We may use your information for
                        other purposes, such as data analysis, identifying usage
                        trends, determining the effectiveness of our promotional
                        campaigns and to evaluate and improve our Service,
                        products, services, marketing and your experience.
                      </li>
                    </ul>
                  </article>
                  <article className="mb-2">
                    <Text as="p" className="mb-1">
                      We may share your personal information in the following
                      situations:
                    </Text>
                    <ul className="ml-4 pl-4 list-disc">
                      <li>
                        With Service Providers: We may share your personal
                        information with service providers to monitor and
                        analyze the use of our Service, to contact you.
                      </li>
                      <li>
                        With your consent: We may disclose your personal
                        information for any other purpose with your consent.
                      </li>
                    </ul>
                  </article>
                  <Text as="p" className="mb-1">
                    For additional clarity, we do not share your personal
                    information with any registered political parties, their
                    constituency associates, candidates, or other
                    representatives.
                  </Text>
                </article>
              </article>
              <article className="mb-6">
                <h3 className="mb-2 font-semibold text-lg">
                  Retention of Your Personal Data
                </h3>
                <Text as="p" className="mb-2">
                  EVOLUTZ will retain your Personal Data only for as long as is
                  necessary for the purposes set out in this Privacy Policy. We
                  will retain and use your Personal Data to the extent necessary
                  to comply with our legal obligations (for example, if we are
                  required to retain your data to comply with applicable laws),
                  resolve disputes, and enforce our legal agreements and
                  policies. <br />
                  EVOLUTZ will also retain Usage Data for internal analysis
                  purposes. Usage data is generally retained for a shorter
                  period of time, except when this data is used to strengthen
                  the security or to improve the functionality of our Service,
                  or we are legally obligated to retain this data for longer
                  time periods.
                </Text>
              </article>
              <article className="mb-6">
                <h3 className="mb-2 font-semibold text-lg">
                  Transfer of Your Personal Data
                </h3>
                <Text as="p" className="mb-2">
                  Your information, including Personal Data, is processed at
                  EVOLUTZ operating offices and in any other places where the
                  parties involved in the processing are located. It means that
                  this information may be transferred to — and maintained on —
                  computers located outside of your province, territory, country
                  or other governmental jurisdiction where the data protection
                  laws may differ than those from your jurisdiction. <br />
                  Your consent to this Privacy Policy followed by your
                  submission of such information represents your agreement to
                  that transfer. <br />
                  EVOLUTZ will take all steps reasonably necessary to ensure
                  that your data is treated securely and in accordance with this
                  Privacy Policy and no transfer of your Personal Data will take
                  place to an organization or a country unless there are
                  adequate controls in place including the security of your data
                  and other personal information.
                </Text>
              </article>
              <article className="mb-6">
                <h3 className="mb-2 font-semibold text-lg">
                  Request to be “De-indexed”
                </h3>
                <Text as="p" className="mb-2">
                  You may submit a request to us at any time for us to
                  “de-index” your personal data and information. This means, to
                  the extent we may have, cease disseminating any hyperlinks or
                  other archived connections to your personal information or
                  data. <br />
                  For additional clarity, this does not require us to completely
                  delete any and all of your personal data and information that
                  we may have for internal use.
                </Text>
              </article>
              <article className="mb-6">
                <h3 className="mb-2 font-semibold text-lg">
                  Request for your Personal Data and Information
                </h3>
                <Text as="p" className="mb-2">
                  You may submit a request to us at any time for us to provide
                  you with a record of what personal data or information of
                  yours that we have on file (at the time of your request).
                </Text>
              </article>
            </li>
            <li className="mb-12">
              <h2 className="mb-4 font-bold text-xl">
                C. Disclosure of Your Personal Data
              </h2>
              <Text as="p" className="mb-1">
                Law enforcement
              </Text>
              <Text as="p" className="mb-1">
                Under certain circumstances, EVOLUTZ may be required to disclose
                your Personal Data if required to do so by law or in response to
                valid requests by public authorities (e.g. a court or a
                government agency).
              </Text>
              <Text as="p" className="mb-1">
                Other legal requirements
              </Text>
              <article>
                <Text as="p" className="mb-1">
                  EVOLUTZ may disclose your Personal Data in the good faith
                  belief that such action is necessary to:
                </Text>
                <ul className="ml-4 pl-4 list-disc">
                  <li>Comply with a legal obligation;</li>
                  <li>Protect and defend the rights or property of EVOLUTZ;</li>
                  <li>
                    Prevent or investigate possible wrongdoing in connection
                    with the Service;
                  </li>
                  <li>
                    Protect the personal safety of users of the Service or the
                    public; and
                  </li>
                  <li>Protect against legal liability.</li>
                </ul>
              </article>
            </li>
            <li className="mb-12">
              <h2 className="mb-4 font-bold text-xl">
                D. Security of Your Personal Data and Information
              </h2>
              <Text as="p" className="mb-4">
                The security of your Personal Data is important to us, but
                remember that no method of transmission over the internet, or
                method of electronic storage is 100% secure. While we strive to
                use all reasonable means to protect your Personal Data, we
                cannot guarantee its absolute security.
              </Text>
              <article className="mb-6">
                <h3 className="mb-2 font-semibold text-lg">
                  Security Breaches
                </h3>
                <Text as="p" className="mb-2">
                  We record any and all instances of security breaches to our
                  collected personal data and information and will advise you in
                  the event of any security breaches that impact any of our
                  collected personal data and information.
                </Text>
              </article>
              <article className="mb-6">
                <h3 className="mb-2 font-semibold text-lg">
                  Personal Information Assessments (“PIA”)
                </h3>
                <Text as="p" className="mb-2">
                  We will perform PIAs prior to any transfer, system
                  change/upgrade, or any other activity that may inappropriately
                  expose your personal data and information. PIAs are risk
                  assessments. We will ensure that we always employ reasonable
                  measures with respect to our collection, retention, and use of
                  your personal data and information.
                </Text>
                <article>
                  <h4 className="mb-2 font-semibold text-md">
                    Links to Other Websites
                  </h4>
                  <Text as="p" className="mb-2">
                    Our Service may contain links to other websites that are not
                    operated by us. If you click on a third party link, you will
                    be directed to that third party site. We strongly advise you
                    to review the privacy policy of every site you visit. We
                    have no control over and assume no responsibility for the
                    content, privacy policies or practices of any third party
                    sites or services.
                  </Text>
                </article>
              </article>
            </li>
            <li className="mb-12">
              <h2 className="mb-4 font-bold text-xl">
                E. Changes to this Privacy Policy
              </h2>
              <Text as="p" className="mb-4">
                We may update our Privacy Policy from time to time. We will
                notify you of any changes by posting the new Privacy Policy on
                this page.
                <br />
                We will let you know via email and/or a prominent notice on our
                Service, prior to the change becoming effective and update the
                date at the top of this Privacy Policy.
                <br />
                You are advised to review this Privacy Policy periodically for
                any changes. Changes to this Privacy Policy are effective when
                they are posted on this page.
              </Text>
            </li>
            <li className="mb-12">
              <h2 className="mb-4 font-bold text-xl">F. Privacy Officer</h2>
              <Text as="p" className="mb-4">
                You may contact our Privacy Officer at any time concerning this
                Privacy Policy and/or your personal data and information.
              </Text>
              <article className="mb-6">
                <h3 className="mb-2 font-semibold text-lg">
                  Evolutz Privacy Officer
                </h3>
                <Text className="mb-2 block">Suzanna Alsayed</Text>
                <a href="mailto:service@evolutz.com">
                  <Text color="accent">service@evolutz.com</Text>
                </a>
              </article>
            </li>
          </ol>
        </div>
      </section>
    </>
  );
}
